### ISSUE TITLE
SwitchYard: cannot execute ProjectCreationTest:createProjectWithServerTest

### ISSUE THREAD

**Issue by apodhrad** [jbosstools/jbosstools-integration-stack-tests#174]
java.lang.Exception: No tests found matching Method createProjectWithServerTest(org.jboss.tools.switchyard.ui.bot.test.ProjectCreationTest) from org.junit.internal.requests.ClassRequest@228eb03f
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestMethodReference.<init>(JUnit4TestMethodReference.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:54)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.jboss.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:56)
	at org.jboss.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:115)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)

**Comment by apodhrad** [comment]
We cannot execute any specific test by selecting the test in Run As... dialog

**Comment by apodhrad** [comment]
This is very similar to https://github.com/jboss-reddeer/reddeer/pull/538

**Comment by apodhrad** [comment]
The problem is with xml configurations

**Comment by apodhrad** [comment]
This will be fixed in https://github.com/jboss-reddeer/reddeer/issues/932

**Comment by apodhrad** [comment]
As a workaround is to specify the config file in test method, e.g.
```
createProjectWithOSGiTest switchyard-200.xml
```
