### ISSUE TITLE
SwitchYard: Cannot find tree item in DebuggerTest

### ISSUE THREAD

**Issue by apodhrad** [jbosstools/jbosstools-integration-stack-tests#377]
Error Message

No tree item found. Please see exception details

Stacktrace

org.jboss.reddeer.swt.impl.tree.TreeItemNotFoundException: No tree item found. Please see exception details
	at org.jboss.reddeer.swt.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:78)
	at org.jboss.reddeer.swt.lookup.TreeItemLookup.getTreeItem(TreeItemLookup.java:51)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:46)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:37)
	at org.jboss.tools.switchyard.reddeer.debug.Breakpoint.<init>(Breakpoint.java:53)
	at org.jboss.tools.switchyard.reddeer.debug.BreakpointsView.getBreakpoints(BreakpointsView.java:35)
	at org.jboss.tools.switchyard.ui.bot.test.DebuggerTest.consumerOutDebugTest(DebuggerTest.java:242)

![org jboss tools switchyard ui bot test debuggertest consumeroutdebugtest](https://cloud.githubusercontent.com/assets/2270674/7929808/7ba0a4a2-0902-11e5-9eeb-01ab6706e25e.png)

**Comment by apodhrad** [comment]
on rewok

**Comment by apodhrad** [comment]
This should be already fixed by #639
