### ISSUE TITLE
SwitchYard: Cannot find the right editor in TopDownBPMN2Test

### ISSUE THREAD

**Issue by apodhrad** [jbosstools/jbosstools-integration-stack-tests#378]
Error Message

Unable to find editor matching specified matchers

Stacktrace

org.jboss.reddeer.workbench.exception.WorkbenchPartNotFound: Unable to find editor matching specified matchers
	at org.jboss.reddeer.workbench.lookup.EditorPartLookup.getEditor(EditorPartLookup.java:99)
	at org.jboss.reddeer.workbench.impl.editor.AbstractEditor.<init>(AbstractEditor.java:73)
	at org.jboss.reddeer.workbench.impl.editor.AbstractEditor.<init>(AbstractEditor.java:65)
	at org.jboss.reddeer.workbench.impl.editor.AbstractEditor.<init>(AbstractEditor.java:56)
	at org.jboss.reddeer.workbench.impl.editor.DefaultEditor.<init>(DefaultEditor.java:28)
	at org.jboss.tools.switchyard.ui.bot.test.TopDownBPMN2Test.topDownBPMN2Test(TopDownBPMN2Test.java:125)

This issue was discovered on rewok.

**Comment by apodhrad** [comment]
the test was removed due to its duplicity
