### ISSUE TITLE
Fuse: Add comments to all assert methods

### ISSUE THREAD

**Issue by tsedmik** [jbosstools/jbosstools-integration-stack-tests#406]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.jboss.tools.fuse.ui.bot.test.DebuggerTest.testDebugger(DebuggerTest.java:154)
```

from such a failure is not much obvious where is the problem. This will solve comments within assert calls.

**Comment by tsedmik** [comment]
obsolete
