### ISSUE TITLE
Fuse: Fix 'JMXNavigatorServerTest'

### ISSUE THREAD

**Issue by tsedmik** [jbosstools/jbosstools-integration-stack-tests#540]
see the following error - JBDS 9.0.0.GA, JBoss Fuse 6.2.1.ER4, Fuse Tooling from master

```
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 166.179 sec <<< FAILURE! - in org.jboss.tools.fuse.ui.bot.test.JMXNavigatorServerTest
testServerInJMXNavigator karaf-3.0.3.xml(org.jboss.tools.fuse.ui.bot.test.JMXNavigatorServerTest)  Time elapsed: 73.279 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at org.jboss.tools.fuse.ui.bot.test.JMXNavigatorServerTest.testServerInJMXNavigator(JMXNavigatorServerTest.java:136)

testServerContextOperationsInJMXNavigator karaf-3.0.3.xml(org.jboss.tools.fuse.ui.bot.test.JMXNavigatorServerTest)  Time elapsed: 0.238 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.jboss.tools.fuse.ui.bot.test.JMXNavigatorServerTest.testServerContextOperationsInJMXNavigator(JMXNavigatorServerTest.java:167)


Results :

Failed tests: 
  JMXNavigatorServerTest.testServerInJMXNavigator:136 null

Tests in error: 
  JMXNavigatorServerTest.testServerContextOperationsInJMXNavigator:167 NullPointer

Tests run: 2, Failures: 1, Errors: 1, Skipped: 0
```

**Comment by tsedmik** [comment]
check with JBDSIS 9.0.0.Alpha2

**Comment by tsedmik** [comment]
there is a problem in fuse master build, that cause mentioned errors. The test is OK with the latest JBDSIS build (JBDSIS 9.0.0.Alpha2). I'm going to check the test with JBDSIS 8.0.4.CR2 + the latest build of Fuse Tooling 7.3.2 build.

**Comment by tsedmik** [comment]
JBDSIS 8.0.4.CR2 - OK
the latest build of Fuse Tooling 7.3.2 - FAILED

**Comment by tsedmik** [comment]
Closing - the test is OK with the latest JBDSIS builds
