### ISSUE TITLE
Fuse: Fix CamelEditorTest

### ISSUE THREAD

**Issue by tsedmik** [jbosstools/jbosstools-integration-stack-tests#553]
Windows
```
java.lang.AssertionError: Connection between 'choice' and 'otherwise' wasn't created
	at org.junit.Assert.fail(Assert.java:88)
	at org.jboss.tools.fuse.ui.bot.test.CamelEditorTest.testDragAndDropComponents(CamelEditorTest.java:214)
```

```
java.lang.AssertionError: Content Assistent does not contain 'id' value
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.tools.fuse.ui.bot.test.CamelEditorTest.testCodeCompletion(CamelEditorTest.java:270)
```

Linux (quetzal64)

```
java.lang.AssertionError: Connection between 'choice' and 'otherwise' wasn't created
	at org.junit.Assert.fail(Assert.java:88)
	at org.jboss.tools.fuse.ui.bot.test.CamelEditorTest.testDragAndDropComponents(CamelEditorTest.java:214)
```

Mac
```
15:45:15.402 ERROR [main][CamelEditor] Error during AWT Robot manipulation
```

**Comment by tsedmik** [comment]
problem with AWT on OS X is already reported #424

**Comment by tsedmik** [comment]
Obsolete
